# Generated by Django 4.1.2 on 2022-10-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_alter_conversation_participants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Message',
            new_name='message',
        ),
    ]
