# Generated by Django 4.1.2 on 2022-12-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_bookday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookDay',
            new_name='BookedDay',
        ),
    ]
