# Generated by Django 4.1.2 on 2022-10-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_alter_list_room_alter_list_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='room',
            new_name='rooms',
        ),
    ]
